FROM python:3.11-slim

WORKDIR /etl
ADD pyproject.toml .
RUN pip install --upgrade pip
RUN pip install poetry
RUN poetry config virtualenvs.create false
RUN poetry install --no-root
COPY /postgres_to_es .